services:
  - type: web
    name: Auto_Apply_App_Mobile          # keep the exact name if you already created it
    runtime: static plus
    branch: main
    buildCommand: "echo noop"            # no build step
    staticPublishPath: "."               # serve your current folder
    autoDeploy: true

    # (optional) make sure browsers don't cache old files during your testing
    headers:
      - path: "/*"
        name: Cache-Control
        value: "public, max-age=0, must-revalidate"

    # ⭐ the only thing that matters: proxy /api/* to your backend
    routes:
      - type: rewrite
        source: "/api/*"
        destination: "https://autoapplyapp-backend.onrender.com/api/*"










