# render.yaml — AutoApplyApp
# One blueprint that provisions:
# 1) A Postgres database
# 2) The FastAPI backend (Python)
# 3) A static frontend (served from /frontend_build)

databases:
  - name: autoapply-db
    plan: starter plus  # Updated from 'starter'
    databaseName: autoapply
    user: autoapply_user

services:
  - type: web
    name: autoapply-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autoapply-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"

  - type: static_site
    name: autoapply-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: frontend_build
    envVars:
      - key: BACKEND_URL
        value: https://autoapply-backend.onrender.com




