services:
  - type: web
    name: autoapply-api
    runtime: python
    rootDir: backend
    plan: starter plus
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        sync: false

  - type: web
    name: autoapply-site
    runtime: static
    rootDir: site
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://<YOUR-API>.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html









