services:
  - type: web
    name: autoapply-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DATABASE_URL
        sync: false # Set in Render Dashboard → Environment tab
      - key: SECRET_KEY
        sync: false # Set in Render Dashboard → Environment tab
      - key: CORS_ORIGINS
        value: "*"
      - key: API_BASE_URL
        value: https://autoapply-api.onrender.com

  - type: web
    name: autoapply-frontend
    env: static
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: API_BASE_URL
        value: https://autoapply-api.onrender.com

