SNOWFLAKE_USER = "MAKWANDECAREERS"
SNOWFLAKE_PASSWORD = "Makwande@202530"
SNOWFLAKE_ACCOUNT = "hpfcrwb-oh67940"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "AUTOAPPLY_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"


  



  